### ISSUE TITLE
"Yayit" are missing

### ISSUE THREAD

**Issue by swanhtet1992** [trhura/paytan#13]
When I convert Unicode to Zawgyi, yayit are missing in converted zawgyi.

**Comment by trhura** [comment]
Please, provid the affected input & output.

**Comment by swanhtet1992** [comment]
Tested with Scala converter. It works.

Only javascript converter is not working. Since converters are based on same rules.

![screen shot 2015-02-25 at 11 32 10 pm](https://cloud.githubusercontent.com/assets/772338/6375629/b1722770-bd46-11e4-994d-7e10a2714a48.png)

**Comment by emoosx** [comment]
@swanhtet1992 @trhura I have located the problem and proposed a fix. #14 . Please take a look.

**Comment by trhura** [comment]
Awesome! @swanhtet1992, please confirm @emoosx's commit fixes this issue. Thanks!

**Comment by swanhtet1992** [comment]
Awesome 👍👍👍👍👍
