### ISSUE TITLE
conert this word အဓိ႒ာန္ to Unicode. There, ဋ္ဌ output wrong  like as ဌ္ဋ.

### ISSUE THREAD

**Issue by sanlinnaing** [trhura/paytan#7]
အဓိ႒ာန္ is converted to Unicode as အဓိဌ္ဋာန်. Actually, ဋ္ဌ is encoded as ဋ+္+ဌ.

**Comment by emoosx** [comment]
@sanlinnaing it would be better if you provide more info such as the language in which the conversion is going wrong. As far as I have checked, it's working fine for `အဓိ႒ာန္` ->  `အဓိဋ္ဌာန်`  in `java`, `python`, `javascript`. The conversion [rule] (https://github.com/trhura/paytan/blob/master/converter/zg12uni51.rules#L56) is correct, too. 
`ဋ္ဌ = ဋ + virama + ဌ` so I don't see why the conversion could go wrong. Screenshots attached.

![screen shot 2015-02-20 at 05 24 46](https://cloud.githubusercontent.com/assets/264626/6276478/18c0e4cc-b8c2-11e4-8da1-dba0b0db9ed7.png)
![screen shot 2015-02-20 at 05 25 12](https://cloud.githubusercontent.com/assets/264626/6276479/18d26eb8-b8c2-11e4-8c20-0ec35bb80f4c.png)

Thoughts? @trhura @yelinaung @indexer

**Comment by sanlinnaing** [comment]
Now I check again and again bro. I closed this issues bro. I faced this issues but now it is fixed. This may be my mistake bro. Thanks for your info. ☺
